baseURL: https://ntu-learning-optimization-club.github.io/
languageCode: zh-hant
defaultContentLanguage: zh-hant
title: NTULOC
theme: PaperMod
googleAnalytics: G-NEEFHZ6378
services:
  googleAnalytics:
    ID: G-NEEFHZ6378
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  zh-hant:
    languageName: "Traditional Chinese"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: å­¸ç¿’æ”»ç•¥
          url: posts/roadmap/roadmap
          weight: 5
        - name: æ–‡ç« 
          url: archives
          weight: 10
#        - name: æœå°‹
#          url: search/
#          weight: 20
#        - name: åˆ†é¡
#          url: posts/
#          weight: 10
#        - name: ä¸»é¡Œ
#          url: tags/
#          weight: 10
        - name: é—œæ–¼æˆ‘å€‘
          url: aboutus/
          weight: 20
        - name: æ´»å‹•
          url: activities/
          weight: 10
#        - name: åŠ å…¥æˆ‘å€‘
#          url: joinus/
#          weight: 25
#
params:
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  #ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButton: true
  assets:
    favicon: /images/favicon.png
    favicon16x16: /images/favicon-16x16.png
    favicon32x32: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: /images/safari-pinned-tab.svg
  label:
    text: NTULOC
    icon: /images/favicon.png
    iconHeight: 35
  homeInfoParams:
    Title: NTULOC
    Content:
      <p>- Unlock Your Mind, Learn and Shine.</p>
      <br>
      <h2>ğŸ™‹â€â™‚ï¸æˆ‘å€‘æ˜¯èª°ï¼ŸğŸ™‹â€â™€ï¸</h2>
      <hr> 
      <p>æˆ‘å€‘æ˜¯ä¸€ç¾¤å°æ–¼å­¸ç¿’èˆ‡æ•™è‚²æœ‰ç†±å¿±çš„å­¸ç”Ÿï¼Œé€éç ”ç©¶å­¸ç¿’ç†è«–ã€ä»¥å¯¦é©—é©—è­‰ï¼Œå°‡æ‰å¯¦çš„ç†è«–è½‰åŒ–ç‚ºéˆæ´»çš„å­¸ç¿’æ–¹æ³•ï¼Œåœ¨ç¤¾åœ˜å…§éƒ¨æ¨å»£ï¼Œä¸¦æå‡ç¤¾å“¡çš„å¯¦åŠ›ã€‚</p>
      <br>{{< youtube akUhMOldEx0 >}}<br>
      <h2>ğŸ’â€â™‚ï¸æˆ‘å€‘åœ¨åšä»€éº¼ï¼ŸğŸ’â€â™€ï¸</h2>
      <br>
      <img src="/images/1.png">
      <br>
      <img src="/images/2.png">
      <br>
      <img src="/images/3.png">
      <br>
      <h2>ğŸ’â€â™‚ï¸æˆ‘å€‘æ˜¯ä¸€å€‹æœå‹™æ€§ç¤¾åœ˜ï¼ğŸ’â€â™€ï¸</h2>
      <br>
      <p>åœ¨æˆ‘å€‘å­¸ç¿’ç²¾é€²ä¹‹é¤˜ï¼Œä¹Ÿå°‡é€™äº›æ–°çš„å­¸ç¿’æ–¹æ³•æ¨å»£çµ¦é«˜ä¸­ç”Ÿï¼Œè®“ä»–å€‘çš„å­¸ç¿’ä¸å†åªæ˜¯æ­»è¨˜ç¡¬èƒŒã€‚æˆ‘å€‘æœƒè¾¦ç†å·¥ä½œåŠã€æ ¡åœ’è¬›åº§ã€å­¸ç”Ÿè¼”å°ç­‰æ´»å‹•ï¼Œæ“´å±•é«˜ä¸­ç”Ÿå°æ–¼å­¸ç¿’çš„è¦–é‡ï¼Œè®“ä»–å€‘çœ‹è¦‹å¡«é´¨æ•™è‚²å¤–çš„å¦ä¸€å€‹ä¸–ç•Œã€‚</p>
      <br>
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/_ntuloc_?igsh=MzRlODBiNWFlZA%3D%3D"
    - name: "facebook"
      url: "https://www.facebook.com/profile.php?id=61556688069720" 
  contact:
    email: ntulocclub@gmail.com

output:
  home:
    - HTML
    - RSS
    - JSON
