baseURL: https://ntu-learning-optimization-club.github.io/
languageCode: zh-hant
defaultContentLanguage: zh-hant
title: NTULOC
theme: PaperMod
googleAnalytics: G-NEEFHZ6378
services:
  googleAnalytics:
    ID: G-NEEFHZ6378
markup:
  goldmark:
    renderer:
      unsafe: true
languages:
  zh-hant:
    languageName: "Traditional Chinese"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: æ–‡ç« 
          url: archives
          weight: 5
#        - name: æœå°‹
#          url: search/
#          weight: 20
#        - name: åˆ†é¡
#          url: posts/
#          weight: 10
        - name: ä¸»é¡Œ
          url: tags/
          weight: 10
        - name: é—œæ–¼æˆ‘å€‘
          url: aboutus/
          weight: 20
        - name: æ´»å‹•
          url: activities/
          weight: 15
#        - name: åŠ å…¥æˆ‘å€‘
#          url: joinus/
#          weight: 25
#
params:
  defaultTheme: dark
  disableThemeToggle: true
  env: production
  #ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButton: true
  assets:
    favicon: /images/favicon.png
    favicon16x16: /images/favicon-16x16.png
    favicon32x32: /images/favicon-32x32.png
    apple_touch_icon: /images/apple-touch-icon.png
    safari_pinned_tab: /images/safari-pinned-tab.svg
  label:
    text: NTULOC
    icon: /images/favicon.png
    iconHeight: 35
  homeInfoParams:
    Title: NTULOC
    Content:
      <p>- Unlock Your Mind, Learn and Shine.</p>
      <br>
      <h2>ğŸ™‹â€â™‚ï¸æˆ‘å€‘æ˜¯èª°ï¼ŸğŸ™‹â€â™€ï¸</h2>
      <hr> 
      <p>æˆ‘å€‘æ˜¯ä¸€ç¾¤å°æ–¼å­¸ç¿’èˆ‡æ•™è‚²æœ‰ç†±å¿±çš„å­¸ç”Ÿï¼Œé€éç ”ç©¶å­¸ç¿’ç†è«–ã€ä»¥å¯¦é©—é©—è­‰ï¼Œå°‡æ‰å¯¦çš„ç†è«–è½‰åŒ–ç‚ºéˆæ´»çš„å­¸ç¿’æ–¹æ³•ï¼Œåœ¨ç¤¾åœ˜å…§éƒ¨æ¨å»£ï¼Œä¸¦æå‡ç¤¾å“¡çš„å¯¦åŠ›ã€‚</p>
      <br>{{< youtube akUhMOldEx0 >}}<br>
      <h2>ğŸ’â€â™‚ï¸æˆ‘å€‘åœ¨åšä»€éº¼ï¼ŸğŸ’â€â™€ï¸</h2>
      <img src="/images/1.png">
      <img src="/images/2.png">
      <img src="/images/3.png">
      <h2>ğŸ’â€â™‚ï¸æˆ‘å€‘æ˜¯ä¸€å€‹æœå‹™æ€§ç¤¾åœ˜ï¼ğŸ’â€â™€ï¸</h2>
      <br>
      <p>åœ¨æˆ‘å€‘å­¸ç¿’ç²¾é€²ä¹‹é¤˜ï¼Œä¹Ÿå°‡é€™äº›æ–°çš„å­¸ç¿’æ–¹æ³•æ¨å»£çµ¦é«˜ä¸­ç”Ÿï¼Œè®“ä»–å€‘çš„å­¸ç¿’ä¸å†åªæ˜¯æ­»è¨˜ç¡¬èƒŒã€‚æˆ‘å€‘æœƒè¾¦ç†å·¥ä½œåŠã€æ ¡åœ’è¬›åº§ã€å­¸ç”Ÿè¼”å°ç­‰æ´»å‹•ï¼Œæ“´å±•é«˜ä¸­ç”Ÿå°æ–¼å­¸ç¿’çš„è¦–é‡ï¼Œè®“ä»–å€‘çœ‹è¦‹å¡«é´¨æ•™è‚²å¤–çš„å¦ä¸€å€‹ä¸–ç•Œã€‚</p>
      <br>
      <h2> ä½ å¯ä»¥å­¸åˆ°ä»€éº¼ï¼Ÿ</h2>
      <hr>
      ç¶“æ­·å¤šæ¬¡çš„è³‡æ–™æ”¶é›†å’Œè¨è«–ï¼Œæˆ‘å€‘é‡å°å­¸ç¿’æ–¹æ³•æ•´ç†å‡ºäº†ä¸‰å¤§æ¶æ§‹ã€‚
      <hr>
      <img src="/images/Roadmap.png">
      <ol type="1">
        <li>å°ˆæ³¨èˆ‡æ‹–å»¶</li>
          <ul>
            <li>è•ƒèŒ„é˜ Pomodoro</li>
          </ul>
        <li>å­¸ç¿’æ–¹æ³•ä»‹ç´¹</li>
          <ul>
            <li>ä¸»å‹•å¼å›é¡§ (Active Recall)</li>
            <li>é–“éš”é‡è¤‡ (Spaced Repetition)</li>
            <li>Anki ä½¿ç”¨æ•™å­¸</li>
            <li>é—œæ–¼ç­†è¨˜æ–¹æ³•</li>
          </ul>
        <li>æ™‚é–“èˆ‡ç‹€æ…‹ç®¡ç†</li>
      </ol>
      <br>
      <h2>ğŸš©å‰µç¤¾åˆè¡·ğŸš©</h2>
      <hr>
      <p>åœ¨æˆ‘å€‘æˆé•·çš„éç¨‹ä¸­ï¼Œå¤šå°‘æœƒé‡åˆ°ä¸€äº›èª²æ¥­ä¸Šçš„ä¸é †é‚ã€‚ç„¶è€Œï¼Œæˆ‘å€‘é™¤äº†å¤šçœ‹å¹¾æ¬¡èª²æœ¬ã€å¤šåˆ·é¡Œç›®ï¼Œæˆ–æ­»è¨˜ç¡¬èƒŒä¹‹å¤–ï¼Œç¶“å¸¸ç„¡æ³•æ‰¾åˆ°åˆé©çš„è§£æ±ºæ–¹æ³•ä¾†åº¦éé€™äº›é›£é—œã€‚ ç‚ºä»€éº¼æœƒç™¼ç”Ÿé€™æ¨£çš„ç‹€æ³å‘¢ï¼Ÿ é¦–å…ˆï¼Œå­¸æ ¡æ•™æˆçš„æ˜¯çŸ¥è­˜ï¼Œè€Œä¸æ˜¯çŸ¥è­˜å¸æ”¶çš„æ–¹æ³•ï¼Œç„¶è€Œé€™äº›æ–¹æ³•çš„ç™¼ç¾ç¶“å¸¸æ˜¯å‡ºè‡ªæ–¼å¶ç„¶ï¼Œè€Œä¸æ˜¯æˆ‘å€‘èˆ‡ç”Ÿä¿±ä¾†çš„ã€‚é‹æ°£å¥½çš„ï¼Œç™¼ç¾äº†åˆé©çš„æ–¹æ³•ï¼Œä¾¿é£›é»ƒé¨°é”ï¼›é‹æ°£ä¸å¥½çš„ï¼Œä¾¿æœƒé–‹å§‹æ‡·ç–‘è‡ªå·±ï¼Œæ˜¯ä¸æ˜¯è‡ªå·±ä¸å¤ è°æ˜æˆ–æ˜¯åŠªåŠ›ä¸è¶³ï¼Ÿ è¨±å¤šäººå¿½è¦–çš„ï¼Œå»æ˜¯é‚£æ¢è·¯å¾‘çš„é¸æ“‡ã€‚ å› æ­¤ï¼Œæˆ‘å€‘å¸Œæœ›å¯ä»¥é€éä¸€ç¾¤äººçš„åˆä½œï¼Œä¸€èµ·æ‰¾å‡ºæ›´å¥½çš„ï¼Œç”šè‡³æ˜¯é€šç”¨æ–¼æ‰€æœ‰äººçš„å­¸ç¿’æ–¹æ³•ï¼Œä¸¦æ¨å»£çµ¦æ­£åœ¨å‡å­¸å£“åŠ›ä¸­çš„é«˜ä¸­ç”Ÿã€‚</p>
      <br>
      <h2>ğŸœï¸æˆ‘å€‘æ›¾ç¶“èµ°éçš„é‚£ä¸€æ®µè·¯ğŸœï¸</h2>
      <br>
      <img src="/images/4.png">
      <br>
      <h2>ğŸ‘‰ä½ é©åˆåŠ å…¥æˆ‘å€‘å—ï¼ŸğŸ‘ˆ</h2>
      <br>
      <p>æˆ‘å€‘è‡´åŠ›æ–¼å•Ÿç™¼æ¯ä¸€å€‹äººçš„æ½›èƒ½ï¼Œé€éå‰µæ–°çš„å­¸ç¿’æ–¹å¼ï¼Œå¹«åŠ©å¯¦ç¾æ‰€æœ‰çš„å¤¢æƒ³ã€‚ ä½ ï¼Œå¦‚æœè·Ÿæˆ‘å€‘ä¸€æ¨£ï¼Œå°æ•™è‚²æœ‰ç†±å¿±ï¼Œæƒ³å’Œæˆ‘å€‘ä¸€èµ·æå‡å¯¦åŠ›ï¼Œä¸€èµ·å¹«åŠ©å…¶ä»–å­¸ç”Ÿï¼Œæ­¡è¿åŠ å…¥å°å¤§å­¸ç¿’å„ªåŒ–ç ”ç©¶ç¤¾ï¼Œä¸€èµ·å‰µé€ æ”¹è®Šï¼</p>
  socialIcons:
    - name: "instagram"
      url: "https://www.instagram.com/_ntuloc_?igsh=MzRlODBiNWFlZA%3D%3D"
    - name: "facebook"
      url: "https://www.facebook.com/profile.php?id=61556688069720" 
  contact:
    email: ntulocclub@gmail.com

output:
  home:
    - HTML
    - RSS
    - JSON
